language: node_js
node_js:
  - '0.12'
before_script:
  - mysql -uroot -e "create database edgy_test"

  - npm install bower --global
  - bower install
  - npm run build
after_success:
  'npm run deploy'

env:
  global:
    - secure: xTMGkIkNB5SAESEkKU+EChYHZqzkr9nOEzl0CP6aITKkT8OklwlKJKKa2jzSxgpUPjzTQub22lK1cBzeN2W5VUFiH+v7YakDx2Nfhk+1gZ/RlSUxy2ROkVecgpVAGcdHqM3in3tVbAdXhcNhGpRe9t/DDTNhk9sdEtllvUFhZC8=
    - secure: bMQaC02GIre7uNf/tN3/0bzaRyz3lOeMup88bprzIoMAuU4oQD5aZc7Vj8uBi3fWLJDgMLAeu+tRep1LUf6RGJnrzry/9RBipn3QTl4PeoF6zUFBYZlId3SdDWcgx36sbN9i7va71/4VJWcbPv3NkfcoCsjoOL8Z9T/bDUUWN4U=
    - secure: hP+rl/qLfdsE/qgj8MvdzRfzTxs3p1UCqufnxRazRrh6BSkQRGjSNEn8f/+XcJHUopJk9YcPSzgiJHwPx6JtJK8FhryA5Obeg/hgmi0EJWAvDwm0wtKdXUq9oSXuasH+vw1bB3sFE9FHDCIJXyM/shAnCODrd0YCwqnY5+sQSHw=

addons:
  sauce_connect: true